### Processing the "Chess All GM players Statistics 2023" Dataset.

In [1]:
import pandas as pd
import sklearn as sk
pd.set_option('display.max_columns', 500)

In [2]:
df = pd.read_csv('GM_players_statistics.csv')
print(df.shape)
df.head()

(1508, 35)

,Unnamed: 0,name,username,profile,user_id,title,fide,country,followers,joined,last_online,current_rapid_rating,highest_rapid_rating,highest_rapid_date,rapid_win,rapid_draw,rapid_loss,current_blitz_rating,highest_blitz_rating,highest_blitz_date,blitz_win,blitz_draw,blitz_loss,current_bullet_rating,highest_bullet_rating,highest_bullet_date,bullet_win,bullet_draw,bullet_loss,highest_tactics_rating,highest_tactics_date,highest_puzzle_rush_score,is_streamer,status,league
0,0,Komodo Engine,komodochess,https://www.chess.com/member/KomodoChess,24944922,GM,3411.0,United States,494,07/11/2015,17/09/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400,07/11/2015,NaN,False,premium,NaN
1,1,Vojtěch Plát,vojtechplat,https://www.chess.com/member/VojtechPlat,37712368,GM,2950.0,Czech Republic,360,11/08/2017,13/07/2023,2383.0,2672.0,03/05/2020,12.0,5.0,6.0,2823.0,2914.0,14/07/2020,976.0,280.0,847.0,2661.0,2750.0,27/09/2021,32.0,8.0,47.0,3251,15/09/2021,49.0,False,premium,Bronze
2,2,PlayMagnus Carlsen,playmagnus,https://www.chess.com/member/PlayMagnus,19578862,GM,2882.0,Norway,199,05/11/2014,08/12/2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400,05/11/2014,NaN,False,premium,NaN
3,3,Magnus Carlsen,magnuscarlsen,https://www.chess.com/member/MagnusCarlsen,3889224,GM,2882.0,Norway,142482,27/08/2010,15/07/2023,2925.0,2977.0,07/02/2023,43.0,23.0,8.0,3287.0,3322.0,21/06/2023,1402.0,292.0,334.0,3249.0,3390.0,28/03/2023,662.0,98.0,246.0,400,27/08/2010,NaN,False,premium,Elite
4,4,Fabiano Caruana,fabianocaruana,https://www.chess.com/member/FabianoCaruana,11177810,GM,2835.0,United States,14445,17/03/2013,16/07/2023,2794.0,3045.0,01/09/2019,122.0,103.0,46.0,3125.0,3136.0,28/05/2023,1012.0,194.0,322.0,3030.0,3113.0,30/11/2021,713.0,65.0,203.0,3519,14/06/2023,64.0,False,premium,Crystal

#### Removing Unnecessary Columns

In [3]:
df = df.drop(['highest_rapid_date','highest_blitz_date','highest_bullet_date','profile', 'country', 'joined', 'last_online', 'highest_tactics_date', 'is_streamer', 'status', 'league','title', 'Unnamed: 0', 'username'], axis=1)
df.head()

,name,user_id,fide,followers,current_rapid_rating,highest_rapid_rating,rapid_win,rapid_draw,rapid_loss,current_blitz_rating,highest_blitz_rating,blitz_win,blitz_draw,blitz_loss,current_bullet_rating,highest_bullet_rating,bullet_win,bullet_draw,bullet_loss,highest_tactics_rating,highest_puzzle_rush_score
0,Komodo Engine,24944922,3411.0,494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400,NaN
1,Vojtěch Plát,37712368,2950.0,360,2383.0,2672.0,12.0,5.0,6.0,2823.0,2914.0,976.0,280.0,847.0,2661.0,2750.0,32.0,8.0,47.0,3251,49.0
2,PlayMagnus Carlsen,19578862,2882.0,199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400,NaN
3,Magnus Carlsen,3889224,2882.0,142482,2925.0,2977.0,43.0,23.0,8.0,3287.0,3322.0,1402.0,292.0,334.0,3249.0,3390.0,662.0,98.0,246.0,400,NaN
4,Fabiano Caruana,11177810,2835.0,14445,2794.0,3045.0,122.0,103.0,46.0,3125.0,3136.0,1012.0,194.0,322.0,3030.0,3113.0,713.0,65.0,203.0,3519,64.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1508 entries, 0 to 1507
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   name                       1241 non-null   object
 1   user_id                    1508 non-null   int64
 2   fide                       913 non-null    float64
 3   followers                  1508 non-null   int64
 4   current_rapid_rating       1055 non-null   float64
 5   highest_rapid_rating       997 non-null    float64
 6   rapid_win                  1055 non-null   float64
 7   rapid_draw                 1055 non-null   float64
 8   rapid_loss                 1055 non-null   float64
 9   current_blitz_rating       1388 non-null   float64
 10  highest_blitz_rating       1382 non-null   float64
 11  blitz_win                  1388 non-null   float64
 12  blitz_draw                 1388 non-null   float64
 13  blitz_loss                 1388 non-null   float64
 14  current_bullet_rating      1173 non-null   float64
 15  highest_bullet_rating      1144 non-null   float64
 16  bullet_win                 1173 non-null   float64
 17  bullet_draw                1173 non-null   float64
 18  bullet_loss                1173 non-null   float64
 19  highest_tactics_rating     1508 non-null   int64
 20  highest_puzzle_rush_score  1121 non-null   float64
dtypes: float64(17), int64(3), object(1)
memory usage: 247.5+ KB

In [5]:
df = df.dropna()
df = df.set_index('user_id') # set user_id as index
print(df.shape)
df.head()

(464, 20)

,name,fide,followers,current_rapid_rating,highest_rapid_rating,rapid_win,rapid_draw,rapid_loss,current_blitz_rating,highest_blitz_rating,blitz_win,blitz_draw,blitz_loss,current_bullet_rating,highest_bullet_rating,bullet_win,bullet_draw,bullet_loss,highest_tactics_rating,highest_puzzle_rush_score
user_id,,,,,,,,,,,,,,,,,,,,
37712368,Vojtěch Plát,2950.0,360,2383.0,2672.0,12.0,5.0,6.0,2823.0,2914.0,976.0,280.0,847.0,2661.0,2750.0,32.0,8.0,47.0,3251,49.0
11177810,Fabiano Caruana,2835.0,14445,2794.0,3045.0,122.0,103.0,46.0,3125.0,3136.0,1012.0,194.0,322.0,3030.0,3113.0,713.0,65.0,203.0,3519,64.0
19134490,Iuri Shkuro,2828.0,388,2492.0,2566.0,179.0,4.0,9.0,2906.0,2906.0,977.0,219.0,505.0,2798.0,2798.0,390.0,36.0,192.0,2885,60.0
15448422,Hikaru Nakamura,2814.0,1163963,2781.0,2927.0,156.0,157.0,39.0,3232.0,3332.0,24782.0,3307.0,4284.0,3326.0,3570.0,10920.0,659.0,1536.0,3427,123.0
42022994,Alireza Firouzja,2785.0,18750,2715.0,2837.0,31.0,20.0,18.0,3100.0,3233.0,6266.0,1467.0,3923.0,3264.0,3521.0,11513.0,1326.0,7504.0,3118,73.0

In [12]:
from sklearn.preprocessing import MinMaxScaler

# normalizing the data
scaler = MinMaxScaler()
for column in df.columns:
    if column != 'name' and column != 'user_id':
        df[column] = scaler.fit_transform(df[[column]])
    
df.head()

,name,fide,followers,current_rapid_rating,highest_rapid_rating,rapid_win,rapid_draw,rapid_loss,current_blitz_rating,highest_blitz_rating,blitz_win,blitz_draw,blitz_loss,current_bullet_rating,highest_bullet_rating,bullet_win,bullet_draw,bullet_loss,highest_tactics_rating,highest_puzzle_rush_score
user_id,,,,,,,,,,,,,,,,,,,,
37712368,Vojtěch Plát,1.000000,0.000306,0.776503,0.763924,0.010120,0.004348,0.012270,0.701242,0.714090,0.024141,0.053060,0.030600,0.612245,0.569101,0.000526,0.001637,0.001303,0.569062,0.198381
11177810,Fabiano Caruana,0.961017,0.012407,0.939082,1.000000,0.111316,0.089565,0.094070,0.921841,0.865937,0.025045,0.036763,0.011611,0.827405,0.759853,0.012084,0.013298,0.005630,0.622555,0.259109
19134490,Iuri Shkuro,0.958644,0.000330,0.819620,0.696835,0.163753,0.003478,0.018405,0.761870,0.708618,0.024166,0.041501,0.018230,0.692128,0.594325,0.006602,0.007365,0.005325,0.496008,0.242915
15448422,Hikaru Nakamura,0.953898,1.000000,0.933940,0.925316,0.142594,0.136522,0.079755,1.000000,1.000000,0.621546,0.626682,0.154917,1.000000,1.000000,0.185319,0.134820,0.042599,0.604192,0.497976
42022994,Alireza Firouzja,0.944068,0.016105,0.907832,0.868354,0.027599,0.017391,0.036810,0.903579,0.932285,0.156892,0.277999,0.141860,0.963848,0.974251,0.195384,0.271277,0.208115,0.542515,0.295547

In [13]:
df.to_csv('GM_players_statistics_cleaned.csv')